CREATE TABLE IF NOT EXISTS COMPLIMENTS(
    ID UUID PRIMARY KEY,
    USER_SENDER UUID,
    USER_RECEIVER UUID,
    TAG_ID UUID,
    MESSAGE VARCHAR(255),
    CREATED_AT DATE,
    UPDATED_AT DATE,

    CONSTRAINT FK_UserSenderCompliment FOREIGN KEY(USER_SENDER) REFERENCES USERS(ID) ON DELETE SET NULL ON UPDATE SET NULL,
    CONSTRAINT FK_UserReceiverCompliment FOREIGN KEY(USER_RECEIVER) REFERENCES USERS(ID) ON DELETE SET NULL ON UPDATE SET NULL,
    CONSTRAINT FK_TagCompliment FOREIGN KEY(TAG_ID) REFERENCES TAGS(ID) ON DELETE SET NULL ON UPDATE SET NULL
);